### ISSUE TITLE
How to?

### ISSUE THREAD

**Issue by rcronin** [jhc-systems/debezium-connector-ibmi#33]
How would one build this locally and create a local debezium docker instance?

**Comment by msillence** [comment]
using java 17 you can see our build command in the cloudbuild-release.yaml

Now I look at it from a 3rd party point of view I see that the publish point for docker is GCP and hard coded into the debezium-connector-ibmi/pom.xml 
`eu.gcr.io/${repository.project}/debezium-connector-ibmi`
as is the source image
`eu.gcr.io/${repository.project}/openjdk17:latest`

I'll take a look at making that a parameter so you can use whatever location you want. I guess it would be good to publish an image to hub.docker.com so people don't have to build their own.

currently the latest tag is 1.6.20 so you probably want something like:

mvn -B -P 'jhc.release,!jhc.snapshot' -Drepository.project=myproject -Drevision=1.6.20 -Dchangelist= -DskipNexusStagingDeployMojo=true -DskipITs jib:dockerBuild

the  jib:dockerBuild should publish locally, let me know if you have any issues with dependencies, it might be there are as there is a seperate confluent repo we have in our maven settings.

**Comment by rcronin** [comment]
@msillence thanks for getting back so quickly and providing this. Once this is built, what is in the docker image exactly?

**Comment by msillence** [comment]
Oh and sorry but I was wrong about the version number we are now on 1.7.4, I'd forgotten I was on a branch for a client who is using an older proxy
You can now save yourself the effort of building it as I've published an image at hub.docker.com: silllencem/debezium-connector-ibmi:1.9.2.Final_1.7.4
