### ISSUE TITLE
receiver name not detected

### ISSUE THREAD

**Issue by msillence** [jhc-systems/debezium-connector-ibmi#49]
- It was my bad, I journaled my files with a journal that was not in the *LIB 
=> I Just updated my file and now it detects everythings :open_mouth: 

--> for this constraint, do you think that you'll be able to update it ? I'm not a big java developper but I scrolled through the code and saw this on [this page](https://github.com/jhc-systems/debezium-connector-ibmi/blob/main/journal-parsing/src/main/java/com/fnz/db2/journal/retrieve/JournalInfoRetrieval.java)
![image](https://github.com/jhc-systems/debezium-connector-ibmi/assets/87163807/0217f6b3-c187-42ba-bc6d-ee0526ed9dec)
I think that maybe it's where the problem is. I use a query to get journal info [https://gist.github.com/andymalo43/16231be5805866b523abe3271409a0e5](gist)
![image](https://github.com/jhc-systems/debezium-connector-ibmi/assets/87163807/d11b882f-95a6-4c75-a292-3313acb9ca52)
I hope this can help you :) 

have a great day

And again : Thank you very much for your work :)

_Originally posted by @andymalo43 in https://github.com/jhc-systems/debezium-connector-ibmi/issues/40#issuecomment-1556699739_

**Comment by msillence** [comment]
@andymalo43 thanks for the update, it's great to hear you have it working now and the ccsid is also working

I feel this update about the receiver name and the change request belongs to a seperate issue - which I've cretaed.

The proposed SQL runs very slowly on our iseries so I'm not so keen on that solution. I propose I add a new configuration parameter for the journal receiver so you can set it to something that isn't detected with the existing mechanism.

Does that sound OK to you?

**Comment by andymalo43** [comment]
Hi @msillence,
If I well understand, you think to put a parameter for the lib of the journal of the table to track cdc ? 
I think it'ld be a killer feature for your connector :D

**Comment by msillence** [comment]
OK I think we can get the journal for a table using QDBRTVFD - if you have an include list this will now detect the journal correctly and also fail if the list spans more than one journal (you would need more than one connector configured one for each journal)

https://github.com/jhc-systems/debezium-connector-ibmi/pull/55

**Comment by msillence** [comment]
fixed in release silllencem/debezium-connector-ibmi:2.2.1.Final_1.9.20
