### ISSUE TITLE
Kafka Message is junk data

### ISSUE THREAD

**Issue by rcronin** [jhc-systems/debezium-connector-ibmi#59]
I'm running the docker compose here and getting absolute junk in the kafka message. Am I doing something wrong here?

<img width="1107" alt="image" src="https://github.com/jhc-systems/debezium-connector-ibmi/assets/11710708/c3a25c10-f4ed-433e-897a-48b0c63622fe">

**Comment by msillence** [comment]
It looks like you are viewing the message without avro decoding

All the examples and default config is set for avro, if you use avro for decoding it will probably make more sense

**Comment by rcronin** [comment]
That definitely got the format of the message looking correct. Still having an issue with the data format for numbers, dates, and timestamps. 

<img width="1107" alt="image" src="https://github.com/jhc-systems/debezium-connector-ibmi/assets/11710708/2b52655b-8883-464e-a9d7-0b0ea16c144e">

**Comment by msillence** [comment]
so if you check the avro schema it uses the confluent logical types - some things such as kardrop etc don't seem to support them yet
Dates are represented as an int days since 1970 but with a logical type

eg.
```
{
      "name" : "DATE_JOINED",
      "type" : [ "null", {
        "type" : "int",
        "connect.version" : 1,
        "connect.name" : "io.debezium.time.Date"
      } ],
      "default" : null
    },
```

timestamps by longs:

```
{
      "name" : "MY_TIMESTAMP",
      "type" : {
        "type" : "long",
        "connect.version" : 1,
        "connect.name" : "io.debezium.time.NanoTimestamp"
      }
    },
```

**Comment by rcronin** [comment]
Thanks for looking into this. How should I proceed on this for dates/numbers?

Ryan Cronin, Systems Solutions Architect
Corporate Office
Dayton Freight Lines, Inc.
p. 937.415.1791
f. 937.890.2724
i. 803191
***@***.******@***.***>
www.daytonfreight.com<http://www.daytonfreight.com/>

Delivering Value Today. Driving the Standard for Tomorrow.

From: Martin Sillence ***@***.***>
Date: Wednesday, September 13, 2023 at 10:28 AM
To: jhc-systems/debezium-connector-ibmi ***@***.***>
Cc: Ryan Cronin ***@***.***>, Author ***@***.***>
Subject: Re: [jhc-systems/debezium-connector-ibmi] Kafka Message is junk data (Issue #59)

-This message originated from outside Dayton Freight controlled email systems. Please use caution when clicking on links or providing user credential information (i.e. usernames and passwords.) If in doubt of the email's authenticity contact the HelpDesk.-

so if you check the avro schema it uses the confluent logical types - some things such as kardrop etc don't seem to support them yet
Dates are represented as an int days since 1970 but with a logical type

eg.

{

      "name" : "DATE_JOINED",

      "type" : [ "null", {

        "type" : "int",

        "connect.version" : 1,

        "connect.name" : "io.debezium.time.Date"

      } ],

      "default" : null

    },

timestamps by longs:

{

      "name" : "MY_TIMESTAMP",

      "type" : {

        "type" : "long",

        "connect.version" : 1,

        "connect.name" : "io.debezium.time.NanoTimestamp"

      }

    },

**Comment by rcronin** [comment]
Okay I've tracked it down to just decimal values as having problems.

Here's the schema being used.

```
{
	"name": "FHPRO",
	"type": {
		"type": "bytes",
		"scale": 0,
		"precision": 11,
		"connect.version": 1,
		"connect.parameters": {
			"scale": "0",
			"connect.decimal.precision": "11"
		},
		"connect.name": "org.apache.kafka.connect.data.Decimal",
		"logicalType": "decimal"
	}
}
```

**Comment by msillence** [comment]
That looks correct, if you use avro it can decode them natively I use this in our maven pom.xml to generate the correct code from the avro

```
            <plugin>
                <groupId>org.apache.avro</groupId>
                <artifactId>avro-maven-plugin</artifactId>
                <version>1.11.0</version>
                <executions>
                    <execution>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>schema</goal>
                        </goals>
                        <configuration>
                            <stringType>String</stringType>
                            <enableDecimalLogicalType>true</enableDecimalLogicalType>
                            <sourceDirectory>${project.basedir}/src/main/avro/</sourceDirectory>
                            <outputDirectory>${project.basedir}/target/generated-src/main/java/</outputDirectory>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
```

**Comment by msillence** [comment]
not a bug
