### ISSUE TITLE
Package for Kafka Connect

### ISSUE THREAD

**Issue by snxmlx** [jhc-systems/debezium-connector-ibmi#70]
Hey, is there a way to package the Connector to work with Confluent Kafka Connect?

**Comment by msillence** [comment]
I believe it sould be possible but it's not something we have time to try

**Comment by snxmlx** [comment]
I managed to get it working. Ty for the connector

**Comment by msillence** [comment]
> I managed to get it working. Ty guys for the connector.

You're welcome - do you want to share what was required to make it work?
